## Swimming PSB Challenge

> In the challenge you'll be wrangling the the `swimming_psb` data set to produce the output shown at the bottom of this notebook.

> Keep a [Cheatsheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf) handy? or the [Pandas API Reference in Docs](https://pandas.pydata.org/pandas-docs/stable/reference/index.html)?

In [1]:
import pandas as pd

psb_df = pd.read_csv('data/swimming_psb_data.csv')

psb_df.info()
psb_df.head(7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16948 entries, 0 to 16947
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   c_Sport        16948 non-null  object
 1   c_Season       16948 non-null  int64 
 2   c_Event        16948 non-null  object
 3   c_Gender       16948 non-null  object
 4   n_DateSort     16948 non-null  int64 
 5   c_Person       16640 non-null  object
 6   c_PersonNatio  16640 non-null  object
 7   c_NOC          16948 non-null  object
 8   c_Result       16948 non-null  object
 9   n_ResultSort   16948 non-null  int64 
 10  c_Class        16948 non-null  object
dtypes: int64(3), object(8)
memory usage: 1.4+ MB


c_Sport  c_Season          c_Event c_Gender  n_DateSort  \
0  Swimming      2018  100m Backstroke      Men    20180809   
1  Swimming      2018  100m Backstroke      Men    20180822   
2  Swimming      2018  100m Backstroke      Men    20180806   
3  Swimming      2018  100m Backstroke      Men    20180819   
4  Swimming      2018  100m Backstroke      Men    20180728   
5  Swimming      2018  100m Backstroke      Men    20180809   
6  Swimming      2018  100m Backstroke      Men    20180810   

             c_Person  c_PersonNatio          c_NOC c_Result  n_ResultSort  \
0         Ryan Murphy  United States  United States    51.94         51940   
1            Xu Jiayu          China          China    52.30         52300   
2  Kliment Kolesnikov         Russia         Russia    52.51         52510   
3        Ryosuke Irie          Japan          Japan    52.53         52530   
4        Matt Grevers  United States  United States    52.55         52550   
5       Evgeniy Rylov         Russia         Russia    52.66         52660   
6        Mitch Larkin      Australia      Australia    52.88         52880   

  c_Class  
0   Elite  
1   Elite  
2   Elite  
3   Elite  
4   Elite  
5   Elite  
6   Elite

#### 1. Remove ```c_Sport```, ```c_Season``` and ```c_Class``` columns.
> Because you decide you don't need them...

In [2]:
removecols = ['c_Sport', 'c_Season','c_Class']
psb_df.drop(removecols, inplace=True, axis=1)
psb_df

c_Event c_Gender  n_DateSort            c_Person  \
0      100m Backstroke      Men    20180809         Ryan Murphy   
1      100m Backstroke      Men    20180822            Xu Jiayu   
2      100m Backstroke      Men    20180806  Kliment Kolesnikov   
3      100m Backstroke      Men    20180819        Ryosuke Irie   
4      100m Backstroke      Men    20180728        Matt Grevers   
...                ...      ...         ...                 ...   
16943   800m Freestyle    Women    20180726       Klara Bosnjak   
16944   800m Freestyle    Women    20180519     Chantel Jeffrey   
16945   800m Freestyle    Women    20180421          Bindi Ware   
16946   800m Freestyle    Women    20180302    Ebony Blackstone   
16947   800m Freestyle    Women    20180609      Mia Steen Duus   

       c_PersonNatio          c_NOC c_Result  n_ResultSort  
0      United States  United States    51.94         51940  
1              China          China    52.30         52300  
2             Russia         Russia    52.51         52510  
3              Japan          Japan    52.53         52530  
4      United States  United States    52.55         52550  
...              ...            ...      ...           ...  
16943        Croatia        Croatia  9:02.44        542440  
16944         Canada         Canada  9:02.47        542470  
16945      Australia      Australia  9:02.48        542480  
16946      Australia      Australia  9:02.54        542540  
16947        Denmark        Denmark  9:02.55        542550  

[16948 rows x 8 columns]

#### 2. Output all unique events (```c_Event```).
> Becasue you want to checkout which Swimming events are in the data.

In [3]:
psb_df['c_Event'].unique()

array(['100m Backstroke', '100m Breaststroke', '100m Butterfly',
       '100m Freestyle', '1500m Freestyle', '200m Backstroke',
       '200m Breaststroke', '200m Butterfly', '200m Freestyle',
       '200m Individual Medley', '4 x 100m Freestyle Relay',
       '4 x 100m Medley Relay', '4 x 200m Freestyle Relay',
       '400m Freestyle', '400m Individual Medley', '50m Backstroke',
       '50m Breaststroke', '50m Butterfly', '50m Freestyle',
       '800m Freestyle'], dtype=object)

#### 3a. Find all rows with NaN values.
> Because you want to identify where these values are coming from...more examples [here](https://datatofish.com/rows-with-nan-pandas-dataframe/).

In [4]:
nan_rows = psb_df[psb_df.isnull().any(axis=1)]
nan_rows
# Alternative method
# nan_rows = psb_df[psb_df.isna().any(axis=1)]
# nan_rows

# rows_with_nan_values = psb_df[psb_df.isnull().any(axis=1)]
# rows_with_nan_values

c_Event c_Gender  n_DateSort c_Person c_PersonNatio  \
9743   4 x 100m Freestyle Relay      Men    20180809      NaN           NaN   
9744   4 x 100m Freestyle Relay      Men    20180803      NaN           NaN   
9745   4 x 100m Freestyle Relay      Men    20180809      NaN           NaN   
9746   4 x 100m Freestyle Relay      Men    20180809      NaN           NaN   
9747   4 x 100m Freestyle Relay      Men    20180803      NaN           NaN   
...                         ...      ...         ...      ...           ...   
10046  4 x 200m Freestyle Relay    Women    20180824      NaN           NaN   
10047  4 x 200m Freestyle Relay    Women    20180821      NaN           NaN   
10048  4 x 200m Freestyle Relay    Women    20180708      NaN           NaN   
10049  4 x 200m Freestyle Relay    Women    20180708      NaN           NaN   
10050  4 x 200m Freestyle Relay    Women    20180708      NaN           NaN   

             c_NOC c_Result  n_ResultSort  
9743        Brazil  3:12.02        192020  
9744        Russia  3:12.23        192230  
9745     Australia  3:12.53        192530  
9746         Japan  3:12.54        192540  
9747         Italy  3:12.90        192900  
...            ...      ...           ...  
10046  New Zealand  8:18.91        498910  
10047    Indonesia  8:21.51        501510  
10048     Portugal  8:24.56        504560  
10049     Slovakia  8:27.47        507470  
10050       Turkey  8:28.37        508370  

[308 rows x 8 columns]

#### 3b. Find all Unique values in the ```c_Event``` column from the ```rows_with_nan_values``` you created above.
> Because you want to confirm all the NaN values are coming specificly from relay events maybe???

In [5]:
unique_rows = nan_rows['c_Event'].unique()
unique_rows

array(['4 x 100m Freestyle Relay', '4 x 100m Medley Relay',
       '4 x 200m Freestyle Relay'], dtype=object)

#### 4. Drop all rows in `psb_df` with a NaN values. 
> There are several solutions here...you could actually try provide a value for the missing data...however, in this instance, you decide it's ok to just drop all the rows with NaN values.

In [6]:
dropped_nan_values = psb_df.dropna()
dropped_nan_values

c_Event c_Gender  n_DateSort            c_Person  \
0      100m Backstroke      Men    20180809         Ryan Murphy   
1      100m Backstroke      Men    20180822            Xu Jiayu   
2      100m Backstroke      Men    20180806  Kliment Kolesnikov   
3      100m Backstroke      Men    20180819        Ryosuke Irie   
4      100m Backstroke      Men    20180728        Matt Grevers   
...                ...      ...         ...                 ...   
16943   800m Freestyle    Women    20180726       Klara Bosnjak   
16944   800m Freestyle    Women    20180519     Chantel Jeffrey   
16945   800m Freestyle    Women    20180421          Bindi Ware   
16946   800m Freestyle    Women    20180302    Ebony Blackstone   
16947   800m Freestyle    Women    20180609      Mia Steen Duus   

       c_PersonNatio          c_NOC c_Result  n_ResultSort  
0      United States  United States    51.94         51940  
1              China          China    52.30         52300  
2             Russia         Russia    52.51         52510  
3              Japan          Japan    52.53         52530  
4      United States  United States    52.55         52550  
...              ...            ...      ...           ...  
16943        Croatia        Croatia  9:02.44        542440  
16944         Canada         Canada  9:02.47        542470  
16945      Australia      Australia  9:02.48        542480  
16946      Australia      Australia  9:02.54        542540  
16947        Denmark        Denmark  9:02.55        542550  

[16640 rows x 8 columns]

#### 5. Reset the Index
> Because you've removed some rows, you decide to reset your Dataframe's index (not nessesity in this case, but good practice to do so)

In [7]:
## Resest index column as taking rows out would mean the index is out by (however many rows removed)
    ##inplace=True makes change permanent (overwriting the dropped_nan_values variable - stops you having to create new copies of the dataframe as you're going through)
    ##drop=True drops previous index (which is the on which would be out by x numbers)
## Now we've delted rows, if we wanted to loop through and index by row, we hit a point when we get an index error as it would try and find a row that doesn't ecist - this creates a sequencial list from data we want to keep)
dropped_nan_values.reset_index(inplace=True, drop=True)
dropped_nan_values

c_Event c_Gender  n_DateSort            c_Person  \
0      100m Backstroke      Men    20180809         Ryan Murphy   
1      100m Backstroke      Men    20180822            Xu Jiayu   
2      100m Backstroke      Men    20180806  Kliment Kolesnikov   
3      100m Backstroke      Men    20180819        Ryosuke Irie   
4      100m Backstroke      Men    20180728        Matt Grevers   
...                ...      ...         ...                 ...   
16635   800m Freestyle    Women    20180726       Klara Bosnjak   
16636   800m Freestyle    Women    20180519     Chantel Jeffrey   
16637   800m Freestyle    Women    20180421          Bindi Ware   
16638   800m Freestyle    Women    20180302    Ebony Blackstone   
16639   800m Freestyle    Women    20180609      Mia Steen Duus   

       c_PersonNatio          c_NOC c_Result  n_ResultSort  
0      United States  United States    51.94         51940  
1              China          China    52.30         52300  
2             Russia         Russia    52.51         52510  
3              Japan          Japan    52.53         52530  
4      United States  United States    52.55         52550  
...              ...            ...      ...           ...  
16635        Croatia        Croatia  9:02.44        542440  
16636         Canada         Canada  9:02.47        542470  
16637      Australia      Australia  9:02.48        542480  
16638      Australia      Australia  9:02.54        542540  
16639        Denmark        Denmark  9:02.55        542550  

[16640 rows x 8 columns]

#### 6. Rename all the column headers in the dataframe, so each header makes sense to you...
> e.g. rename ```c_Person``` to ```athlete```...

In [8]:
## call the dataframe, use the .rename method and create a dictionary, calling the columns and replacing the current name with new name for each column)
dropped_nan_values.rename(columns={"c_Event":"Event", "c_Gender":"Gender", "n_DateSort":"Date", "c_Person":"Athlete", "c_PersonNatio":"Nation", "c_NOC":"NOC", "c_Result":"Time(s)", "n_ResultSort":"Time(ms)"},inplace=True)
dropped_nan_values

/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py:4441: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


Event Gender      Date             Athlete         Nation  \
0      100m Backstroke    Men  20180809         Ryan Murphy  United States   
1      100m Backstroke    Men  20180822            Xu Jiayu          China   
2      100m Backstroke    Men  20180806  Kliment Kolesnikov         Russia   
3      100m Backstroke    Men  20180819        Ryosuke Irie          Japan   
4      100m Backstroke    Men  20180728        Matt Grevers  United States   
...                ...    ...       ...                 ...            ...   
16635   800m Freestyle  Women  20180726       Klara Bosnjak        Croatia   
16636   800m Freestyle  Women  20180519     Chantel Jeffrey         Canada   
16637   800m Freestyle  Women  20180421          Bindi Ware      Australia   
16638   800m Freestyle  Women  20180302    Ebony Blackstone      Australia   
16639   800m Freestyle  Women  20180609      Mia Steen Duus        Denmark   

                 NOC  Time(s)  Time(ms)  
0      United States    51.94     51940  
1              China    52.30     52300  
2             Russia    52.51     52510  
3              Japan    52.53     52530  
4      United States    52.55     52550  
...              ...      ...       ...  
16635        Croatia  9:02.44    542440  
16636         Canada  9:02.47    542470  
16637      Australia  9:02.48    542480  
16638      Australia  9:02.54    542540  
16639        Denmark  9:02.55    542550  

[16640 rows x 8 columns]

#### 7. Transform each value in the ```date_sort``` column into a DateTime Object using the [```.to_datetime```](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html) method.
> Because it's better to handle dates as actual DateTime objects in Python...

In [9]:
dropped_nan_values["Date"] = pd.to_datetime(dropped_nan_values["Date"].astype(str), format='%Y%m%d')
dropped_nan_values
## add this to the end after the bracket to remove 00:00:00, but converts to object not datetime64: .dt.strftime('%Y-%m-%d')

/tmp/ipykernel_1018/11701234.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropped_nan_values["Date"] = pd.to_datetime(dropped_nan_values["Date"].astype(str), format='%Y%m%d')


Event Gender       Date             Athlete         Nation  \
0      100m Backstroke    Men 2018-08-09         Ryan Murphy  United States   
1      100m Backstroke    Men 2018-08-22            Xu Jiayu          China   
2      100m Backstroke    Men 2018-08-06  Kliment Kolesnikov         Russia   
3      100m Backstroke    Men 2018-08-19        Ryosuke Irie          Japan   
4      100m Backstroke    Men 2018-07-28        Matt Grevers  United States   
...                ...    ...        ...                 ...            ...   
16635   800m Freestyle  Women 2018-07-26       Klara Bosnjak        Croatia   
16636   800m Freestyle  Women 2018-05-19     Chantel Jeffrey         Canada   
16637   800m Freestyle  Women 2018-04-21          Bindi Ware      Australia   
16638   800m Freestyle  Women 2018-03-02    Ebony Blackstone      Australia   
16639   800m Freestyle  Women 2018-06-09      Mia Steen Duus        Denmark   

                 NOC  Time(s)  Time(ms)  
0      United States    51.94     51940  
1              China    52.30     52300  
2             Russia    52.51     52510  
3              Japan    52.53     52530  
4      United States    52.55     52550  
...              ...      ...       ...  
16635        Croatia  9:02.44    542440  
16636         Canada  9:02.47    542470  
16637      Australia  9:02.48    542480  
16638      Australia  9:02.54    542540  
16639        Denmark  9:02.55    542550  

[16640 rows x 8 columns]

#### 8. Create a column for each athlete's ```first name``` and ```last name```.
> Seems futile, but you decide this may save you ALOT of time in the future...

In [10]:
##create new variable, split the string of the athlete column by the space, (n=1 means splits on first time it see's the delimiter, so won't triple split a double barrel), and expand to 2 columns##
# first_last_names = dropped_nan_values['Athlete'].str.split(" ", n=1, expand = True)
# ## create a new column in the dataframe called first name and add the new (1st) column from first_last_names##
# dropped_nan_values['First Name'] = first_last_names [0]
# ## create another new column in the dataframe called last name and add the new (2nd) column from first_last_names##
# dropped_nan_values['Last Name'] = first_last_names [1]
# dropped_nan_values

##can do on one line##
dropped_nan_values[['First Name', 'Last Name']] = dropped_nan_values['Athlete'].str.split(" ", n=1, expand = True)[[0,1]]
dropped_nan_values


/shared-libs/python3.9/py/lib/python3.9/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


Event Gender       Date             Athlete         Nation  \
0      100m Backstroke    Men 2018-08-09         Ryan Murphy  United States   
1      100m Backstroke    Men 2018-08-22            Xu Jiayu          China   
2      100m Backstroke    Men 2018-08-06  Kliment Kolesnikov         Russia   
3      100m Backstroke    Men 2018-08-19        Ryosuke Irie          Japan   
4      100m Backstroke    Men 2018-07-28        Matt Grevers  United States   
...                ...    ...        ...                 ...            ...   
16635   800m Freestyle  Women 2018-07-26       Klara Bosnjak        Croatia   
16636   800m Freestyle  Women 2018-05-19     Chantel Jeffrey         Canada   
16637   800m Freestyle  Women 2018-04-21          Bindi Ware      Australia   
16638   800m Freestyle  Women 2018-03-02    Ebony Blackstone      Australia   
16639   800m Freestyle  Women 2018-06-09      Mia Steen Duus        Denmark   

                 NOC  Time(s)  Time(ms) First Name   Last Name  
0      United States    51.94     51940       Ryan      Murphy  
1              China    52.30     52300         Xu       Jiayu  
2             Russia    52.51     52510    Kliment  Kolesnikov  
3              Japan    52.53     52530    Ryosuke        Irie  
4      United States    52.55     52550       Matt     Grevers  
...              ...      ...       ...        ...         ...  
16635        Croatia  9:02.44    542440      Klara     Bosnjak  
16636         Canada  9:02.47    542470    Chantel     Jeffrey  
16637      Australia  9:02.48    542480      Bindi        Ware  
16638      Australia  9:02.54    542540      Ebony  Blackstone  
16639        Denmark  9:02.55    542550        Mia  Steen Duus  

[16640 rows x 10 columns]

#### Finale: Have a final Dataframe that contains only the top (up to 4) Great British swimmers for each event and gender. Then save this data into a new csv or json file.
> Hint: The dataset you have been handling is already sorted and grouped. Fastest swimmers (top four) would be at the top of each group (gender/event).

In [ ]:
## create new variable and select just GB athletes ##
# GB = dropped_nan_values.loc[dropped_nan_values['NOC'] == 'Great Britain']
# ##from this new dataframe, group by event and gender, and .head(4) picks the top 4 from each group - then reset the index and drop=True remvoes the old index)
# Top_4_GB = GB.groupby(['Event','Gender']).head(4).reset_index(drop=True)
# Top_4_GB
## as data is already sorted by time then when you choose.head(4) it will pick the fastest 4
    ## if wasn't already, could sort first by the time column and then go from that

##In one line....##
GB = dropped_nan_values.loc[dropped_nan_values['NOC'] == 'Great Britain'].groupby(['Event','Gender']).head(4).reset_index(drop=True)
GB

Event Gender       Date               Athlete         Nation  \
0    100m Backstroke    Men 2018-04-07  Chris Walker-Hebborn        England   
1    100m Backstroke    Men 2018-04-06        Luke Greenbank        England   
2    100m Backstroke    Men 2018-08-06         Nicholas Pyle  Great Britain   
3    100m Backstroke    Men 2018-04-06       Xavier Castelli          Wales   
4    100m Backstroke  Women 2018-08-06        Georgia Davies          Wales   
..               ...    ...        ...                   ...            ...   
131   800m Freestyle    Men 2018-07-07         Nathan Hughes  Great Britain   
132   800m Freestyle  Women 2018-04-09         Holly Hibbott        England   
133   800m Freestyle  Women 2018-04-09    Camilla Hattersley       Scotland   
134   800m Freestyle  Women 2018-04-08         Jazmin Carlin          Wales   
135   800m Freestyle  Women 2018-07-25          Polly Holden  Great Britain   

               NOC  Time(s)  Time(ms) First Name       Last Name  
0    Great Britain    54.23     54230      Chris  Walker-Hebborn  
1    Great Britain    54.37     54370       Luke       Greenbank  
2    Great Britain    54.50     54500   Nicholas            Pyle  
3    Great Britain    54.60     54600     Xavier        Castelli  
4    Great Britain    59.12     59120    Georgia          Davies  
..             ...      ...       ...        ...             ...  
131  Great Britain  8:05.15    485150     Nathan          Hughes  
132  Great Britain  8:29.05    509050      Holly         Hibbott  
133  Great Britain  8:32.65    512650    Camilla      Hattersley  
134  Great Britain  8:36.52    516520     Jazmin          Carlin  
135  Great Britain  8:38.73    518730      Polly          Holden  

[136 rows x 10 columns]

### Bonus

**The aim is to create a visualisation** that shows the performance standards for each gender and event relative to the respective world record at the time. This visualisation uses world record times (2018) found in the `world_records_swimming.json` file (`data` folder). To enable a visualisation that can show both genders and all the events, at once, requires us to standardise the results data. We can do this by creating another ***result*** that is the relevent world record as a percentage of the actual result e.g.


> **Men 100m Backstroke - Ryan Murphy, United States - `51.94` (seconds) or `51940` (milliseconds)**


In [12]:
import json

wrs = json.load(open('data/world_records_swimming.json'))

wr_secs = float(wrs['Men']['100m Backstroke'])
result = 51.94

wr_percentage = wr_secs / result * 100

round(wr_percentage, 2)


99.83

> Hints

1. Include any relevant cleaning steps in the cell below before attempting to create the new column with the percentage data.
2. Note that some of the world record times are not in seconds. It may be an idea to reformat the world records into milliseconds?
3. We import [```seaborn```](https://seaborn.pydata.org/generated/seaborn.violinplot.html) to create the Violin Plots. e.g. https://seaborn.pydata.org/generated/seaborn.violinplot.html

In [13]:
import json
import pandas as pd
import seaborn as sns

wrs = json.load(open('data/world_records_swimming.json'))  # Pandas is not always nessisary when handling data, a simple dictionary can be far simpler to handle ;)

psb_viz_df = pd.read_csv('data/swimming_psb_data.csv')


##### Reference Image
![BonusViz](./data/swimming_challenge.png)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=82522c04-b10e-4808-ba92-f37909eae5ea' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>